# Where to Learn More {.unnumbered}

This reader provides an introduction to the basics of R, but there's lots more
to learn!

DataLab's [Intermediate R][intermediate-r] workshops are designed specifically
for learners who have taken this workshop and want to learn more about R.

[intermediate-r]: https://ucdavisdatalab.github.io/workshop_intermediate_r/

DataLab also teaches [many other workshops about data science][workshops]. If
you're not sure where to start or how these workshops all fit together, take a
look at our [Reproducibility Principles and Practices reader][repro].

[workshops]: https://datalab.ucdavis.edu/workshops/descriptions/
[repro]: https://ucdavisdatalab.github.io/workshop_reproducible_research/


If you want to learn more about how to design clear and effective data
visualizations, take a look at our [Principles of Data Visualization
reader][data-viz].

[data-viz]: https://ucdavisdatalab.github.io/workshop_data_viz_principles/

Many R and data science learning resources are available for free online or
through the library. Here are a few books created by others that we've found
useful:

* [R for Data Science][r4ds] by Wickham & Grolemund. An introduction to using R
  for data science, but with a very heavy focus on Tidyverse packages.
* [The Art of R Programming][art-of-r] by Matloff. A general reference on R
  programming.
* [Advanced R][adv-r] by Wickham. A description of how R works at a deeper
  level, with many examples of R features that are important for
  package/software development.
* [The R Inferno][r-inferno] by Burns. A discussion of the most difficult and
  confusing parts of R.

[r4ds]: http://r4ds.had.co.nz/
[art-of-r]: https://ebookcentral.proquest.com/lib/ucdavis/detail.action?docID=1137514
[adv-r]: https://adv-r.hadley.nz/
[r-inferno]: http://www.burns-stat.com/documents/books/the-r-inferno/

Finally, here are some websites popular in the R community:

* [R Graph Gallery](http://www.r-graph-gallery.com/). Examples of graphs you
  can make in R, with code.
* [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/). Cheat
  sheets for a variety of R tools and packages.
* [R Weekly](https://rweekly.org/). Weekly updates about what's happening in
  the R community.
* [R-bloggers](https://www.r-bloggers.com/). An aggregator for blog posts
  about R.
